# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Photo Gallery
email: shakedzy@gmail.com
description: A gallery of photos taken by me.
full_name: Shaked Zychlinski
baseurl: "/photo-gallery" # the subpath of your site, e.g. /blog
url: "https://shakedzy.xyz" # the base hostname & protocol for your site
google_analytics: UA-141245946-1
include: ["_pages"]

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "photography"
    values:
      permalink: /:path/:basename:output_ext

exclude: [LICENSE, LICENSE-CODE.md, LICENSE-IMAGES, README.md, bower.json]
